name: Build LKM for Re:Kernel
on:
  workflow_dispatch:
jobs:
  build-lkm:
    strategy:
      matrix:
        include:
          - kmi: android16-6.12-2025-06
    uses: ./.github/workflows/ddk-lkm.yml
    with:
      kmi: ${{ matrix.kmi }}
